### ISSUE TITLE
License for library usage?

### ISSUE THREAD

**Issue by pombredanne** [ArchiveTeam/wpull#336]
I was wondering if you had considered using the LGPL such that wpull could also be used as a library?

**Comment by ethus3h** [comment]
This is licensed under GPL3, so it can be used as a library; just make sure you release your source code (which you should anyway, IMO). LGPL just lets companies take advantage of libre software to make their own non-libre software. Note that I am neither a lawyer nor a wpull maintainer, and this comment should not be taken as a statement of legal advice (rather, it should be taken as my 2¢ from the peanut gallery).

**Comment by chfoo** [comment]
ethus3h covered most of question. I don't plan to license under LGPL since I would like to encourage sharing of contributions. LGPL would undercut the time and effort spent working on Wpull. This project has become a bit too complex to maintain and fixing the technical debt is a big burden.

If someone wants to package Wpull into their non-libre application, I can dual license if they give me briefcases stuffed with cash. :stuck_out_tongue:
