### ISSUE TITLE
What's the difference with wget?

### ISSUE THREAD

**Issue by BarbzYHOOL** [ArchiveTeam/wpull#388]
That looks like it's the same parameters. It looks as complex as Wget in top of that.

just asking because I don't have an easy solution to make backup of sites and wget and its tons of options is annoying

**Comment by JustAnotherArchivist** [comment]
Yes, wpull is designed to be a drop-in replacement for wget, i.e. you could replace `wget` with `wpull` in a command line and it would do the same thing. In practice, that doesn't *always* work, but in many common cases, it does.

The documentation has a page on the differences: https://wpull.readthedocs.io/en/master/differences.html

Parallel retrievals, a URL queue database (rather than storing everything in memory), and a straightforward plugin interface in Python are probably the most important advantages over wget from my point of view.

If you just want to grab a website for local safekeeping and don't want to deal with all the options of wget/wpull directly, have a look at [grab-site](https://github.com/ludios/grab-site). It's essentially a wrapper and interface around wpull.

**Comment by BarbzYHOOL** [comment]
grab-site also requires to set all the options and the interface is only to display progress (from the screenshot)

but I'll have a look at it, thank you (unless there is another alternative)

**Comment by JustAnotherArchivist** [comment]
There are significantly fewer options on grab-site than on wpull, but of course you still need to configure *something*. After all, you have to tell the tool what to grab, e.g. do you want it to follow links to external pages and which links to ignore, and how to grab it (concurrency, delay, user agent, etc.). There is no way to do that in a generic way...

By the way, if you only want to archive individual pages (rather than entire websites), you could also have a look at warcprox. If you run that and define it as a proxy in your browser, it will archive everything you access in the browser into a WARC file. That's as close to zero configuration as you'll get.

**Comment by JustAnotherArchivist** [comment]
The question has been answered, and there was no further activity in almost 4 months... Closing.
Please feel free to reply, reopen, or create another issue if there are further questions.
